import type { Metadata } from "next";
import { Noto_Serif } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/Navbar";


const noto = Noto_Serif({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body className={noto.className}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
